#ifndef _MYSOCKETS_H_
#define _MYSOCKETS_H_


// Define names of socket types
#define TCP_PURPOSE_GENERIC_TCP_CLIENT 0
#define TCP_PURPOSE_GENERIC_TCP_SERVER 1
#define TCP_PURPOSE_TELNET 2
#define TCP_PURPOSE_FTP_COMMAND 3
#define TCP_PURPOSE_FTP_DATA 4
#define TCP_PURPOSE_TCP_PERFORMANCE_TX 5
#define TCP_PURPOSE_TCP_PERFORMANCE_RX 6
#define TCP_PURPOSE_UART_2_TCP_BRIDGE 7
#define TCP_PURPOSE_HTTP_SERVER 8
#define TCP_PURPOSE_DEFAULT 9
#define TCP_PURPOSE_BERKELEY_SERVER 10
#define TCP_PURPOSE_BERKELEY_CLIENT 11
#define TCP_PURPOSE_MYIPDATA_UART1 12
#define TCP_PURPOSE_MYIPDATA_UART2 13
#define TCP_PURPOSE_MYIPDATA_FLYBYWIRE 14
#define TCP_PURPOSE_MYIPDATA_MAVLINK 15
#define TCP_PURPOSE_MYIPDATA_DEBUG 16
#define TCP_PURPOSE_MYIPDATA_ADSB 17
#define TCP_PURPOSE_MYIPDATA_LOGO 18
#define TCP_PURPOSE_MYIPDATA_CAM_TRACK 19
#define TCP_PURPOSE_MYIPDATA_GPSTEST 20
#define TCP_PURPOSE_MYIPDATA_PWMREPORT 21
#define TCP_PURPOSE_MYIPDATA_XPLANE 22
#define TCP_PURPOSE_MYIPDATA_TELEMETRY_EXTRA 23
#define TCP_PURPOSE_MYIPDATA_GROUND_STATION 24
#define TCP_PURPOSE_MYIPDATA_AIRCRAFT_CONFIG 25


typedef struct
{
	BYTE vSocketPurpose;
	BYTE vMemoryMedium;
	WORD wTXBufferSize;
	WORD wRXBufferSize;
} TCPSocketInitializer_t;


WORD getMySocketCount(void);
TCPSocketInitializer_t* getMySocketInitializer(WORD i);


#endif // _MYSOCKETS_H_
