#ifndef LOGO2_TABLES_H
#define LOGO2_TABLES_H

// This defines all the elements used within the UDB logo language
// These elements are then described by logo2_table.c for machine communication

typedef enum {
    LOGO_TURTLE_PLANE = 0,
    LOGO_TURTLE_CAMERA,
} LOGO_TURTLES_e;


typedef enum
{
    LOGO_FLIGHTPLAN_MAIN = 0,
    LOGO_FLIGHTPLAN_RTL,
    LOGO_FLIGHTPLAN_SECOND,
    LOGO_FLIGHTPLAN_RAM,
    LOGO_FLIGHTPLAN_NONE,
} LOGO_FLIGHTPLANS_e;

typedef enum
{
    LOGO_CMD_INVALID = 0,
    LOGO_CMD_REPEAT,
    LOGO_CMD_END,
    LOGO_CMD_ELSE,
    LOGO_CMD_TO,

    LOGO_CMD_DO,
    LOGO_CMD_EXEC,

    LOGO_CMD_FD,

    LOGO_CMD_RT,
    LOGO_CMD_SET_ANGLE,
    LOGO_CMD_USE_CURRENT_ANGLE,
    LOGO_CMD_USE_ANGLE_TO_GOAL,

    LOGO_CMD_MV_X,
    LOGO_CMD_SET_X,
    LOGO_CMD_MV_Y,
    LOGO_CMD_SET_Y,
    LOGO_CMD_MV_Z,
    LOGO_CMD_SET_Z,

    LOGO_CMD_USE_CURRENT_POS,
    LOGO_CMD_HOME,

    LOGO_CMD_SET_ABS_VAL_HIGH,
    LOGO_CMD_SET_ABS_X_LOW,
    LOGO_CMD_SET_ABS_Y_LOW,
    LOGO_CMD_SET_ABS_X_Y,

    LOGO_CMD_FLAG_ON,
    LOGO_CMD_FLAG_OFF,
    LOGO_CMD_FLAG_TOGGLE,

    LOGO_CMD_PEN_UP,
    LOGO_CMD_PEN_DOWN,
    LOGO_CMD_PEN_TOGGLE,

    LOGO_CMD_SET_TURTLE,

    LOGO_CMD_PARAM_SET,
    LOGO_CMD_PARAM_ADD,
    LOGO_CMD_PARAM_MUL,
    LOGO_CMD_PARAM_DIV,

    LOGO_CMD_SPEED_INCREASE,
    LOGO_CMD_SET_SPEED,

    LOGO_CMD_SET_INTERRUPT,
    LOGO_CMD_CLEAR_INTERRUPT,

    LOGO_CMD_LOAD_TO_PARAM,

    LOGO_CMD_IF_EQ,
    LOGO_CMD_IF_NE,
    LOGO_CMD_IF_GT,
    LOGO_CMD_IF_LT,
    LOGO_CMD_IF_GE,
    LOGO_CMD_IF_LE,
    LOGO_LOW_CMD_MAX,
} LOGO_LOW_COMMANDS_e;


// Define enumeration of High-level commands for machine communication
// Enumeration stars with last value in the low level commands for a linear list
typedef enum
{
    LOGO_HCMD_FD = LOGO_LOW_CMD_MAX,

    LOGO_HCMD_BK,
    LOGO_HCMD_FD_PARAM,
    LOGO_HCMD_BK_PARAM,

    LOGO_HCMD_RT,
    LOGO_HCMD_LT,
    LOGO_HCMD_SET_ANGLE,
    LOGO_HCMD_RT_PARAM,
    LOGO_HCMD_LT_PARAM,
    LOGO_HCMD_SET_ANGLE_PARAM,
    LOGO_HCMD_USE_CURRENT_ANGLE,
    LOGO_HCMD_USE_ANGLE_TO_GOAL,

    LOGO_HCMD_EAST,
    LOGO_HCMD_WEST,
    LOGO_HCMD_SET_X_POS,
    LOGO_HCMD_EAST_PARAM,
    LOGO_HCMD_WEST_PARAM,
    LOGO_HCMD_SET_X_POS_PARAM,
    LOGO_HCMD_USE_CURRENT_POS,

    LOGO_HCMD_NORTH,
    LOGO_HCMD_SOUTH,
    LOGO_HCMD_SET_Y_POS,
    LOGO_HCMD_NORTH_PARAM,
    LOGO_HCMD_SOUTH_PARAM,
    LOGO_HCMD_SET_Y_POS_PARAM,

    LOGO_HCMD_ALT_UP,
    LOGO_HCMD_ALT_DOWN,
    LOGO_HCMD_SET_ALT,
    LOGO_HCMD_ALT_UP_PARAM,
    LOGO_HCMD_ALT_DOWN_PARAM,
    LOGO_HCMD_SET_ALT_PARAM,

    LOGO_HCMD_SPEED_INCREASE,
    LOGO_HCMD_SPEED_DECREASE,
    LOGO_HCMD_SET_SPEED,
    LOGO_HCMD_SPEED_INCREASE_PARAM,
    LOGO_HCMD_SPEED_DECREASE_PARAM,
    LOGO_HCMD_SET_SPEED_PARAM,

    LOGO_HCMD_FLAG_ON,
    LOGO_HCMD_FLAG_OFF,
    LOGO_HCMD_FLAG_TOGGLE,

    LOGO_HCMD_PEN_UP,
    LOGO_HCMD_PEN_DOWN,
    LOGO_HCMD_PEN_TOGGLE,

    LOGO_HCMD_SET_TURTLE,

    LOGO_HCMD_REPEAT,
    LOGO_HCMD_REPEAT_PARAM,
    LOGO_HCMD_REPEAT_FOREVER,
    LOGO_HCMD_END,
    LOGO_HCMD_ELSE,

    LOGO_HCMD_TO,

    LOGO_HCMD_DO,
    LOGO_HCMD_DO_ARG,
    LOGO_HCMD_DO_PARAM,

    LOGO_HCMD_EXEC,
    LOGO_HCMD_EXEC_ARG,
    LOGO_HCMD_EXEC_PARAM,

    LOGO_HCMD_PARAM_SET,
    LOGO_HCMD_PARAM_ADD,
    LOGO_HCMD_PARAM_SUB,
    LOGO_HCMD_PARAM_MUL,
    LOGO_HCMD_PARAM_DIV,

    LOGO_HCMD_SET_INTERRUPT,
    LOGO_HCMD_CLEAR_INTERRUPT,

    LOGO_HCMD_LOAD_TO_PARAM,

    LOGO_HCMD_IF_EQ,
    LOGO_HCMD_IF_NE,
    LOGO_HCMD_IF_GT,
    LOGO_HCMD_IF_LT,
    LOGO_HCMD_IF_GE,
    LOGO_HCMD_IF_LE,
    LOGO_HCMD_IF_EQ_PARAM,
    LOGO_HCMD_IF_NE_PARAM,
    LOGO_HCMD_IF_GT_PARAM,
    LOGO_HCMD_IF_LT_PARAM,
    LOGO_HCMD_IF_GE_PARAM,
    LOGO_HCMD_IF_LE_PARAM,

    LOGO_HCMD_SET_POS,
    LOGO_HCMD_SET_ABS_POS,
    LOGO_HCMD_HOME,

} LOGO_HIGH_COMMANDS_e;


// Define the conditional VAL values for IF commands
typedef enum {
	LOGO_VAL_ZERO = 0,
	// XX_INPUT_CHANNEL // leave room for input channels: 1 - NUM_INPUTS (up to 15)
	LOGO_VAL_DIST_TO_HOME = 16,
	LOGO_VAL_DIST_TO_GOAL,
	LOGO_VAL_ALT,
	LOGO_VAL_CURRENT_ANGLE,
	LOGO_VAL_ANGLE_TO_HOME,
	LOGO_VAL_ANGLE_TO_GOAL,
	LOGO_VAL_REL_ANGLE_TO_HOME,
	LOGO_VAL_REL_ANGLE_TO_GOAL,
	LOGO_VAL_GROUND_SPEED,
	LOGO_VAL_AIR_SPEED,
	LOGO_VAL_AIR_SPEED_Z,
	LOGO_VAL_WIND_SPEED,
	LOGO_VAL_WIND_SPEED_X,
	LOGO_VAL_WIND_SPEED_Y,
	LOGO_VAL_WIND_SPEED_Z,
	LOGO_VAL_PARAM
} LOGO_VALUE_REFS_e;




#endif    // LOGO2_TABLES_H
