#ifndef LOGO2_TABLES_H
#define LOGO2_TABLES_H


typedef enum
{
    LOGO_FLIGHTPLAN_MAIN = 0,
    LOGO_FLIGHTPLAN_RTL,
    LOGO_FLIGHTPLAN_SECOND,
    LOGO_FLIGHTPLAN_RAM,
    LOGO_FLIGHTPLAN_NONE,
} LOGO_FLIGHTPLANS;


typedef enum
{
	LOGO_CMD_INVALID = 0,
	LOGO_CMD_REPEAT,
	LOGO_CMD_END,
	LOGO_CMD_ELSE,
	LOGO_CMD_TO,

	LOGO_CMD_DO,
	LOGO_CMD_EXEC,

	LOGO_CMD_FD,

	LOGO_CMD_RT,
	LOGO_CMD_SET_ANGLE,
	LOGO_CMD_USE_CURRENT_ANGLE,
	LOGO_CMD_USE_ANGLE_TO_GOAL,

	LOGO_CMD_MV_X,
	LOGO_CMD_SET_X,
	LOGO_CMD_MV_Y,
	LOGO_CMD_SET_Y,
	LOGO_CMD_MV_Z,
	LOGO_CMD_SET_Z,

	LOGO_CMD_USE_CURRENT_POS,
	LOGO_CMD_HOME,

	LOGO_CMD_SET_ABS_VAL_HIGH,
	LOGO_CMD_SET_ABS_X_LOW,
	LOGO_CMD_SET_ABS_Y_LOW,
	LOGO_CMD_SET_ABS_X_Y,

	LOGO_CMD_FLAG_ON,
	LOGO_CMD_FLAG_OFF,
	LOGO_CMD_FLAG_TOGGLE,

	LOGO_CMD_PEN_UP,
	LOGO_CMD_PEN_DOWN,
	LOGO_CMD_PEN_TOGGLE,

	LOGO_CMD_SET_TURTLE,

	LOGO_CMD_PARAM_SET,
	LOGO_CMD_PARAM_ADD,
	LOGO_CMD_PARAM_MUL,
	LOGO_CMD_PARAM_DIV,

	LOGO_CMD_SPEED_INCREASE,
	LOGO_CMD_SET_SPEED,

	LOGO_CMD_SET_INTERRUPT,
	LOGO_CMD_CLEAR_INTERRUPT,

	LOGO_CMD_LOAD_TO_PARAM,

	LOGO_CMD_IF_EQ,
	LOGO_CMD_IF_NE,
	LOGO_CMD_IF_GT,
	LOGO_CMD_IF_LT,
	LOGO_CMD_IF_GE,
	LOGO_CMD_IF_LE,
	LOGO_LOW_CMD_MAX,
} eLOGO_LOW_COMMANDS;


#endif    // LOGO2_TABLES_H
