#!/usr/bin/env python
# -*- coding: utf-8 -*-

#
# Generated Sat May  2 11:00:31 2015 by generateDS.py version 2.15b.
#
# Command line options:
#   ('-o', 'ParameterDatabase.py')
#   ('-s', 'SubParameterDatabase.py')
#
# Command line arguments:
#   ParameterDatabase.xsd
#
# Command line:
#   /usr/local/bin/generateDS.py -o "ParameterDatabase.py" -s "SubParameterDatabase.py" ParameterDatabase.xsd
#
# Current working directory (os.getcwd()):
#   pyparam
#

import sys
import re as re_
import base64
import datetime as datetime_
import warnings as warnings_
from lxml import etree as etree_


Validate_simpletypes_ = True


def parsexml_(*args, **kwargs):
    if 'parser' not in kwargs:
        # Use the lxml ElementTree compatible parser so that, e.g.,
        #   we ignore comments.
        kwargs['parser'] = etree_.ETCompatXMLParser()
    doc = etree_.parse(*args, **kwargs)
    return doc

#
# User methods
#
# Calls to the methods in these classes are generated by generateDS.py.
# You can replace these methods by re-implementing the following class
#   in a module named generatedssuper.py.

try:
    from generatedssuper import GeneratedsSuper
except ImportError as exp:

    class GeneratedsSuper(object):
        tzoff_pattern = re_.compile(r'(\+|-)((0\d|1[0-3]):[0-5]\d|14:00)$')
        class _FixedOffsetTZ(datetime_.tzinfo):
            def __init__(self, offset, name):
                self.__offset = datetime_.timedelta(minutes=offset)
                self.__name = name
            def utcoffset(self, dt):
                return self.__offset
            def tzname(self, dt):
                return self.__name
            def dst(self, dt):
                return None
        def gds_format_string(self, input_data, input_name=''):
            return input_data
        def gds_validate_string(self, input_data, node=None, input_name=''):
            if not input_data:
                return ''
            else:
                return input_data
        def gds_format_base64(self, input_data, input_name=''):
            return base64.b64encode(input_data)
        def gds_validate_base64(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_integer(self, input_data, input_name=''):
            return '%d' % input_data
        def gds_validate_integer(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_integer_list(self, input_data, input_name=''):
            return '%s' % ' '.join(input_data)
        def gds_validate_integer_list(
                self, input_data, node=None, input_name=''):
            values = input_data.split()
            for value in values:
                try:
                    int(value)
                except (TypeError, ValueError):
                    raise_parse_error(node, 'Requires sequence of integers')
            return values
        def gds_format_float(self, input_data, input_name=''):
            return ('%.15f' % input_data).rstrip('0')
        def gds_validate_float(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_float_list(self, input_data, input_name=''):
            return '%s' % ' '.join(input_data)
        def gds_validate_float_list(
                self, input_data, node=None, input_name=''):
            values = input_data.split()
            for value in values:
                try:
                    float(value)
                except (TypeError, ValueError):
                    raise_parse_error(node, 'Requires sequence of floats')
            return values
        def gds_format_double(self, input_data, input_name=''):
            return '%e' % input_data
        def gds_validate_double(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_double_list(self, input_data, input_name=''):
            return '%s' % ' '.join(input_data)
        def gds_validate_double_list(
                self, input_data, node=None, input_name=''):
            values = input_data.split()
            for value in values:
                try:
                    float(value)
                except (TypeError, ValueError):
                    raise_parse_error(node, 'Requires sequence of doubles')
            return values
        def gds_format_boolean(self, input_data, input_name=''):
            return ('%s' % input_data).lower()
        def gds_validate_boolean(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_boolean_list(self, input_data, input_name=''):
            return '%s' % ' '.join(input_data)
        def gds_validate_boolean_list(
                self, input_data, node=None, input_name=''):
            values = input_data.split()
            for value in values:
                if value not in ('true', '1', 'false', '0', ):
                    raise_parse_error(
                        node,
                        'Requires sequence of booleans '
                        '("true", "1", "false", "0")')
            return values
        def gds_validate_datetime(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_datetime(self, input_data, input_name=''):
            if input_data.microsecond == 0:
                _svalue = '%04d-%02d-%02dT%02d:%02d:%02d' % (
                    input_data.year,
                    input_data.month,
                    input_data.day,
                    input_data.hour,
                    input_data.minute,
                    input_data.second,
                )
            else:
                _svalue = '%04d-%02d-%02dT%02d:%02d:%02d.%s' % (
                    input_data.year,
                    input_data.month,
                    input_data.day,
                    input_data.hour,
                    input_data.minute,
                    input_data.second,
                    ('%f' % (float(input_data.microsecond) / 1000000))[2:],
                )
            if input_data.tzinfo is not None:
                tzoff = input_data.tzinfo.utcoffset(input_data)
                if tzoff is not None:
                    total_seconds = tzoff.seconds + (86400 * tzoff.days)
                    if total_seconds == 0:
                        _svalue += 'Z'
                    else:
                        if total_seconds < 0:
                            _svalue += '-'
                            total_seconds *= -1
                        else:
                            _svalue += '+'
                        hours = total_seconds // 3600
                        minutes = (total_seconds - (hours * 3600)) // 60
                        _svalue += '{0:02d}:{1:02d}'.format(hours, minutes)
            return _svalue
        @classmethod
        def gds_parse_datetime(cls, input_data):
            tz = None
            if input_data[-1] == 'Z':
                tz = GeneratedsSuper._FixedOffsetTZ(0, 'UTC')
                input_data = input_data[:-1]
            else:
                results = GeneratedsSuper.tzoff_pattern.search(input_data)
                if results is not None:
                    tzoff_parts = results.group(2).split(':')
                    tzoff = int(tzoff_parts[0]) * 60 + int(tzoff_parts[1])
                    if results.group(1) == '-':
                        tzoff *= -1
                    tz = GeneratedsSuper._FixedOffsetTZ(
                        tzoff, results.group(0))
                    input_data = input_data[:-6]
            time_parts = input_data.split('.')
            if len(time_parts) > 1:
                micro_seconds = int(float('0.' + time_parts[1]) * 1000000)
                input_data = '%s.%s' % (time_parts[0], micro_seconds, )
                dt = datetime_.datetime.strptime(
                    input_data, '%Y-%m-%dT%H:%M:%S.%f')
            else:
                dt = datetime_.datetime.strptime(
                    input_data, '%Y-%m-%dT%H:%M:%S')
            dt = dt.replace(tzinfo=tz)
            return dt
        def gds_validate_date(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_date(self, input_data, input_name=''):
            _svalue = '%04d-%02d-%02d' % (
                input_data.year,
                input_data.month,
                input_data.day,
            )
            try:
                if input_data.tzinfo is not None:
                    tzoff = input_data.tzinfo.utcoffset(input_data)
                    if tzoff is not None:
                        total_seconds = tzoff.seconds + (86400 * tzoff.days)
                        if total_seconds == 0:
                            _svalue += 'Z'
                        else:
                            if total_seconds < 0:
                                _svalue += '-'
                                total_seconds *= -1
                            else:
                                _svalue += '+'
                            hours = total_seconds // 3600
                            minutes = (total_seconds - (hours * 3600)) // 60
                            _svalue += '{0:02d}:{1:02d}'.format(hours, minutes)
            except AttributeError:
                pass
            return _svalue
        @classmethod
        def gds_parse_date(cls, input_data):
            tz = None
            if input_data[-1] == 'Z':
                tz = GeneratedsSuper._FixedOffsetTZ(0, 'UTC')
                input_data = input_data[:-1]
            else:
                results = GeneratedsSuper.tzoff_pattern.search(input_data)
                if results is not None:
                    tzoff_parts = results.group(2).split(':')
                    tzoff = int(tzoff_parts[0]) * 60 + int(tzoff_parts[1])
                    if results.group(1) == '-':
                        tzoff *= -1
                    tz = GeneratedsSuper._FixedOffsetTZ(
                        tzoff, results.group(0))
                    input_data = input_data[:-6]
            dt = datetime_.datetime.strptime(input_data, '%Y-%m-%d')
            dt = dt.replace(tzinfo=tz)
            return dt.date()
        def gds_validate_time(self, input_data, node=None, input_name=''):
            return input_data
        def gds_format_time(self, input_data, input_name=''):
            if input_data.microsecond == 0:
                _svalue = '%02d:%02d:%02d' % (
                    input_data.hour,
                    input_data.minute,
                    input_data.second,
                )
            else:
                _svalue = '%02d:%02d:%02d.%s' % (
                    input_data.hour,
                    input_data.minute,
                    input_data.second,
                    ('%f' % (float(input_data.microsecond) / 1000000))[2:],
                )
            if input_data.tzinfo is not None:
                tzoff = input_data.tzinfo.utcoffset(input_data)
                if tzoff is not None:
                    total_seconds = tzoff.seconds + (86400 * tzoff.days)
                    if total_seconds == 0:
                        _svalue += 'Z'
                    else:
                        if total_seconds < 0:
                            _svalue += '-'
                            total_seconds *= -1
                        else:
                            _svalue += '+'
                        hours = total_seconds // 3600
                        minutes = (total_seconds - (hours * 3600)) // 60
                        _svalue += '{0:02d}:{1:02d}'.format(hours, minutes)
            return _svalue
        def gds_validate_simple_patterns(self, patterns, target):
            # pat is a list of lists of strings/patterns.  We should:
            # - AND the outer elements
            # - OR the inner elements
            found1 = True
            for patterns1 in patterns:
                found2 = False
                for patterns2 in patterns1:
                    if re_.search(patterns2, target) is not None:
                        found2 = True
                        break
                if not found2:
                    found1 = False
                    break
            return found1
        @classmethod
        def gds_parse_time(cls, input_data):
            tz = None
            if input_data[-1] == 'Z':
                tz = GeneratedsSuper._FixedOffsetTZ(0, 'UTC')
                input_data = input_data[:-1]
            else:
                results = GeneratedsSuper.tzoff_pattern.search(input_data)
                if results is not None:
                    tzoff_parts = results.group(2).split(':')
                    tzoff = int(tzoff_parts[0]) * 60 + int(tzoff_parts[1])
                    if results.group(1) == '-':
                        tzoff *= -1
                    tz = GeneratedsSuper._FixedOffsetTZ(
                        tzoff, results.group(0))
                    input_data = input_data[:-6]
            if len(input_data.split('.')) > 1:
                dt = datetime_.datetime.strptime(input_data, '%H:%M:%S.%f')
            else:
                dt = datetime_.datetime.strptime(input_data, '%H:%M:%S')
            dt = dt.replace(tzinfo=tz)
            return dt.time()
        def gds_str_lower(self, instring):
            return instring.lower()
        def get_path_(self, node):
            path_list = []
            self.get_path_list_(node, path_list)
            path_list.reverse()
            path = '/'.join(path_list)
            return path
        Tag_strip_pattern_ = re_.compile(r'\{.*\}')
        def get_path_list_(self, node, path_list):
            if node is None:
                return
            tag = GeneratedsSuper.Tag_strip_pattern_.sub('', node.tag)
            if tag:
                path_list.append(tag)
            self.get_path_list_(node.getparent(), path_list)
        def get_class_obj_(self, node, default_class=None):
            class_obj1 = default_class
            if 'xsi' in node.nsmap:
                classname = node.get('{%s}type' % node.nsmap['xsi'])
                if classname is not None:
                    names = classname.split(':')
                    if len(names) == 2:
                        classname = names[1]
                    class_obj2 = globals().get(classname)
                    if class_obj2 is not None:
                        class_obj1 = class_obj2
            return class_obj1
        def gds_build_any(self, node, type_name=None):
            return None
        @classmethod
        def gds_reverse_node_mapping(cls, mapping):
            return dict(((v, k) for k, v in mapping.iteritems()))


#
# If you have installed IPython you can uncomment and use the following.
# IPython is available from http://ipython.scipy.org/.
#

## from IPython.Shell import IPShellEmbed
## args = ''
## ipshell = IPShellEmbed(args,
##     banner = 'Dropping into IPython',
##     exit_msg = 'Leaving Interpreter, back to program.')

# Then use the following line where and when you want to drop into the
# IPython shell:
#    ipshell('<some message> -- Entering ipshell.\nHit Ctrl-D to exit')

#
# Globals
#

ExternalEncoding = 'ascii'
Tag_pattern_ = re_.compile(r'({.*})?(.*)')
String_cleanup_pat_ = re_.compile(r"[\n\r\s]+")
Namespace_extract_pat_ = re_.compile(r'{(.*)}(.*)')
CDATA_pattern_ = re_.compile(r"<!\[CDATA\[.*?\]\]>", re_.DOTALL)

#
# Support/utility functions.
#


def showIndent(outfile, level, pretty_print=True):
    if pretty_print:
        for idx in range(level):
            outfile.write('    ')


def quote_xml(inStr):
    "Escape markup chars, but do not modify CDATA sections."
    if not inStr:
        return ''
    s1 = (isinstance(inStr, basestring) and inStr or
          '%s' % inStr)
    s2 = ''
    pos = 0
    matchobjects = CDATA_pattern_.finditer(s1)
    for mo in matchobjects:
        s3 = s1[pos:mo.start()]
        s2 += quote_xml_aux(s3)
        s2 += s1[mo.start():mo.end()]
        pos = mo.end()
    s3 = s1[pos:]
    s2 += quote_xml_aux(s3)
    return s2


def quote_xml_aux(inStr):
    s1 = inStr.replace('&', '&amp;')
    s1 = s1.replace('<', '&lt;')
    s1 = s1.replace('>', '&gt;')
    return s1


def quote_attrib(inStr):
    s1 = (isinstance(inStr, basestring) and inStr or
          '%s' % inStr)
    s1 = s1.replace('&', '&amp;')
    s1 = s1.replace('<', '&lt;')
    s1 = s1.replace('>', '&gt;')
    if '"' in s1:
        if "'" in s1:
            s1 = '"%s"' % s1.replace('"', "&quot;")
        else:
            s1 = "'%s'" % s1
    else:
        s1 = '"%s"' % s1
    return s1


def quote_python(inStr):
    s1 = inStr
    if s1.find("'") == -1:
        if s1.find('\n') == -1:
            return "'%s'" % s1
        else:
            return "'''%s'''" % s1
    else:
        if s1.find('"') != -1:
            s1 = s1.replace('"', '\\"')
        if s1.find('\n') == -1:
            return '"%s"' % s1
        else:
            return '"""%s"""' % s1


def get_all_text_(node):
    if node.text is not None:
        text = node.text
    else:
        text = ''
    for child in node:
        if child.tail is not None:
            text += child.tail
    return text


def find_attr_value_(attr_name, node):
    attrs = node.attrib
    attr_parts = attr_name.split(':')
    value = None
    if len(attr_parts) == 1:
        value = attrs.get(attr_name)
    elif len(attr_parts) == 2:
        prefix, name = attr_parts
        namespace = node.nsmap.get(prefix)
        if namespace is not None:
            value = attrs.get('{%s}%s' % (namespace, name, ))
    return value


class GDSParseError(Exception):
    pass


def raise_parse_error(node, msg):
    if XMLParser_import_library == XMLParser_import_lxml:
        msg = '%s (element %s/line %d)' % (
            msg, node.tag, node.sourceline, )
    else:
        msg = '%s (element %s)' % (msg, node.tag, )
    raise GDSParseError(msg)


class MixedContainer:
    # Constants for category:
    CategoryNone = 0
    CategoryText = 1
    CategorySimple = 2
    CategoryComplex = 3
    # Constants for content_type:
    TypeNone = 0
    TypeText = 1
    TypeString = 2
    TypeInteger = 3
    TypeFloat = 4
    TypeDecimal = 5
    TypeDouble = 6
    TypeBoolean = 7
    TypeBase64 = 8
    def __init__(self, category, content_type, name, value):
        self.category = category
        self.content_type = content_type
        self.name = name
        self.value = value
    def getCategory(self):
        return self.category
    def getContenttype(self, content_type):
        return self.content_type
    def getValue(self):
        return self.value
    def getName(self):
        return self.name
    def export(self, outfile, level, name, namespace, pretty_print=True):
        if self.category == MixedContainer.CategoryText:
            # Prevent exporting empty content as empty lines.
            if self.value.strip():
                outfile.write(self.value)
        elif self.category == MixedContainer.CategorySimple:
            self.exportSimple(outfile, level, name)
        else:    # category == MixedContainer.CategoryComplex
            self.value.export(outfile, level, namespace, name, pretty_print)
    def exportSimple(self, outfile, level, name):
        if self.content_type == MixedContainer.TypeString:
            outfile.write('<%s>%s</%s>' % (
                self.name, self.value, self.name))
        elif self.content_type == MixedContainer.TypeInteger or \
                self.content_type == MixedContainer.TypeBoolean:
            outfile.write('<%s>%d</%s>' % (
                self.name, self.value, self.name))
        elif self.content_type == MixedContainer.TypeFloat or \
                self.content_type == MixedContainer.TypeDecimal:
            outfile.write('<%s>%f</%s>' % (
                self.name, self.value, self.name))
        elif self.content_type == MixedContainer.TypeDouble:
            outfile.write('<%s>%g</%s>' % (
                self.name, self.value, self.name))
        elif self.content_type == MixedContainer.TypeBase64:
            outfile.write('<%s>%s</%s>' % (
                self.name, base64.b64encode(self.value), self.name))
    def to_etree(self, element):
        if self.category == MixedContainer.CategoryText:
            # Prevent exporting empty content as empty lines.
            if self.value.strip():
                if len(element) > 0:
                    if element[-1].tail is None:
                        element[-1].tail = self.value
                    else:
                        element[-1].tail += self.value
                else:
                    if element.text is None:
                        element.text = self.value
                    else:
                        element.text += self.value
        elif self.category == MixedContainer.CategorySimple:
            subelement = etree_.SubElement(element, '%s' % self.name)
            subelement.text = self.to_etree_simple()
        else:    # category == MixedContainer.CategoryComplex
            self.value.to_etree(element)
    def to_etree_simple(self):
        if self.content_type == MixedContainer.TypeString:
            text = self.value
        elif (self.content_type == MixedContainer.TypeInteger or
                self.content_type == MixedContainer.TypeBoolean):
            text = '%d' % self.value
        elif (self.content_type == MixedContainer.TypeFloat or
                self.content_type == MixedContainer.TypeDecimal):
            text = '%f' % self.value
        elif self.content_type == MixedContainer.TypeDouble:
            text = '%g' % self.value
        elif self.content_type == MixedContainer.TypeBase64:
            text = '%s' % base64.b64encode(self.value)
        return text
    def exportLiteral(self, outfile, level, name):
        if self.category == MixedContainer.CategoryText:
            showIndent(outfile, level)
            outfile.write(
                'model_.MixedContainer(%d, %d, "%s", "%s"),\n' % (
                    self.category, self.content_type, self.name, self.value))
        elif self.category == MixedContainer.CategorySimple:
            showIndent(outfile, level)
            outfile.write(
                'model_.MixedContainer(%d, %d, "%s", "%s"),\n' % (
                    self.category, self.content_type, self.name, self.value))
        else:    # category == MixedContainer.CategoryComplex
            showIndent(outfile, level)
            outfile.write(
                'model_.MixedContainer(%d, %d, "%s",\n' % (
                    self.category, self.content_type, self.name,))
            self.value.exportLiteral(outfile, level + 1)
            showIndent(outfile, level)
            outfile.write(')\n')


class MemberSpec_(object):
    def __init__(self, name='', data_type='', container=0):
        self.name = name
        self.data_type = data_type
        self.container = container
    def set_name(self, name): self.name = name
    def get_name(self): return self.name
    def set_data_type(self, data_type): self.data_type = data_type
    def get_data_type_chain(self): return self.data_type
    def get_data_type(self):
        if isinstance(self.data_type, list):
            if len(self.data_type) > 0:
                return self.data_type[-1]
            else:
                return 'xs:string'
        else:
            return self.data_type
    def set_container(self, container): self.container = container
    def get_container(self): return self.container


def _cast(typ, value):
    if typ is None or value is None:
        return value
    return typ(value)

#
# Data representation classes.
#


class SerialisationFlags(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, serialisationFlag=None):
        self.original_tagname_ = None
        if serialisationFlag is None:
            self.serialisationFlag = []
        else:
            self.serialisationFlag = serialisationFlag
    def factory(*args_, **kwargs_):
        if SerialisationFlags.subclass:
            return SerialisationFlags.subclass(*args_, **kwargs_)
        else:
            return SerialisationFlags(*args_, **kwargs_)
    factory = staticmethod(factory)
    def get_serialisationFlag(self): return self.serialisationFlag
    def set_serialisationFlag(self, serialisationFlag): self.serialisationFlag = serialisationFlag
    def add_serialisationFlag(self, value): self.serialisationFlag.append(value)
    def insert_serialisationFlag_at(self, index, value): self.serialisationFlag.insert(index, value)
    def replace_serialisationFlag_at(self, index, value): self.serialisationFlag[index] = value
    def hasContent_(self):
        if (
            self.serialisationFlag
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='SerialisationFlags', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='SerialisationFlags')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='SerialisationFlags', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='SerialisationFlags'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='SerialisationFlags', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        for serialisationFlag_ in self.serialisationFlag:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sserialisationFlag>%s</%sserialisationFlag>%s' % (namespace_, self.gds_format_string(quote_xml(serialisationFlag_).encode(ExternalEncoding), input_name='serialisationFlag'), namespace_, eol_))
    def exportLiteral(self, outfile, level, name_='SerialisationFlags'):
        level += 1
        already_processed = set()
        self.exportLiteralAttributes(outfile, level, already_processed, name_)
        if self.hasContent_():
            self.exportLiteralChildren(outfile, level, name_)
    def exportLiteralAttributes(self, outfile, level, already_processed, name_):
        pass
    def exportLiteralChildren(self, outfile, level, name_):
        showIndent(outfile, level)
        outfile.write('serialisationFlag=[\n')
        level += 1
        for serialisationFlag_ in self.serialisationFlag:
            showIndent(outfile, level)
            outfile.write('%s,\n' % quote_python(serialisationFlag_).encode(ExternalEncoding))
        level -= 1
        showIndent(outfile, level)
        outfile.write('],\n')
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'serialisationFlag':
            serialisationFlag_ = child_.text
            serialisationFlag_ = self.gds_validate_string(serialisationFlag_, node, 'serialisationFlag')
            self.serialisationFlag.append(serialisationFlag_)
# end class SerialisationFlags


class UDBType(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, typeName=None, sendFunction=None, setFunction=None, mavlinkType=None):
        self.original_tagname_ = None
        self.typeName = typeName
        self.sendFunction = sendFunction
        self.setFunction = setFunction
        self.mavlinkType = mavlinkType
    def factory(*args_, **kwargs_):
        if UDBType.subclass:
            return UDBType.subclass(*args_, **kwargs_)
        else:
            return UDBType(*args_, **kwargs_)
    factory = staticmethod(factory)
    def get_typeName(self): return self.typeName
    def set_typeName(self, typeName): self.typeName = typeName
    def get_sendFunction(self): return self.sendFunction
    def set_sendFunction(self, sendFunction): self.sendFunction = sendFunction
    def get_setFunction(self): return self.setFunction
    def set_setFunction(self, setFunction): self.setFunction = setFunction
    def get_mavlinkType(self): return self.mavlinkType
    def set_mavlinkType(self, mavlinkType): self.mavlinkType = mavlinkType
    def hasContent_(self):
        if (
            self.typeName is not None or
            self.sendFunction is not None or
            self.setFunction is not None or
            self.mavlinkType is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='UDBType', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='UDBType')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='UDBType', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='UDBType'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='UDBType', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.typeName is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%stypeName>%s</%stypeName>%s' % (namespace_, self.gds_format_string(quote_xml(self.typeName).encode(ExternalEncoding), input_name='typeName'), namespace_, eol_))
        if self.sendFunction is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%ssendFunction>%s</%ssendFunction>%s' % (namespace_, self.gds_format_string(quote_xml(self.sendFunction).encode(ExternalEncoding), input_name='sendFunction'), namespace_, eol_))
        if self.setFunction is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%ssetFunction>%s</%ssetFunction>%s' % (namespace_, self.gds_format_string(quote_xml(self.setFunction).encode(ExternalEncoding), input_name='setFunction'), namespace_, eol_))
        if self.mavlinkType is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%smavlinkType>%s</%smavlinkType>%s' % (namespace_, self.gds_format_string(quote_xml(self.mavlinkType).encode(ExternalEncoding), input_name='mavlinkType'), namespace_, eol_))
    def exportLiteral(self, outfile, level, name_='UDBType'):
        level += 1
        already_processed = set()
        self.exportLiteralAttributes(outfile, level, already_processed, name_)
        if self.hasContent_():
            self.exportLiteralChildren(outfile, level, name_)
    def exportLiteralAttributes(self, outfile, level, already_processed, name_):
        pass
    def exportLiteralChildren(self, outfile, level, name_):
        if self.typeName is not None:
            showIndent(outfile, level)
            outfile.write('typeName=%s,\n' % quote_python(self.typeName).encode(ExternalEncoding))
        if self.sendFunction is not None:
            showIndent(outfile, level)
            outfile.write('sendFunction=%s,\n' % quote_python(self.sendFunction).encode(ExternalEncoding))
        if self.setFunction is not None:
            showIndent(outfile, level)
            outfile.write('setFunction=%s,\n' % quote_python(self.setFunction).encode(ExternalEncoding))
        if self.mavlinkType is not None:
            showIndent(outfile, level)
            outfile.write('mavlinkType=%s,\n' % quote_python(self.mavlinkType).encode(ExternalEncoding))
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'typeName':
            typeName_ = child_.text
            typeName_ = self.gds_validate_string(typeName_, node, 'typeName')
            self.typeName = typeName_
        elif nodeName_ == 'sendFunction':
            sendFunction_ = child_.text
            sendFunction_ = self.gds_validate_string(sendFunction_, node, 'sendFunction')
            self.sendFunction = sendFunction_
        elif nodeName_ == 'setFunction':
            setFunction_ = child_.text
            setFunction_ = self.gds_validate_string(setFunction_, node, 'setFunction')
            self.setFunction = setFunction_
        elif nodeName_ == 'mavlinkType':
            mavlinkType_ = child_.text
            mavlinkType_ = self.gds_validate_string(mavlinkType_, node, 'mavlinkType')
            self.mavlinkType = mavlinkType_
# end class UDBType


class UDBTypes(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, udbType=None):
        self.original_tagname_ = None
        if udbType is None:
            self.udbType = []
        else:
            self.udbType = udbType
    def factory(*args_, **kwargs_):
        if UDBTypes.subclass:
            return UDBTypes.subclass(*args_, **kwargs_)
        else:
            return UDBTypes(*args_, **kwargs_)
    factory = staticmethod(factory)
    def get_udbType(self): return self.udbType
    def set_udbType(self, udbType): self.udbType = udbType
    def add_udbType(self, value): self.udbType.append(value)
    def insert_udbType_at(self, index, value): self.udbType.insert(index, value)
    def replace_udbType_at(self, index, value): self.udbType[index] = value
    def hasContent_(self):
        if (
            self.udbType
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='UDBTypes', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='UDBTypes')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='UDBTypes', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='UDBTypes'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='UDBTypes', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        for udbType_ in self.udbType:
            udbType_.export(outfile, level, namespace_, name_='udbType', pretty_print=pretty_print)
    def exportLiteral(self, outfile, level, name_='UDBTypes'):
        level += 1
        already_processed = set()
        self.exportLiteralAttributes(outfile, level, already_processed, name_)
        if self.hasContent_():
            self.exportLiteralChildren(outfile, level, name_)
    def exportLiteralAttributes(self, outfile, level, already_processed, name_):
        pass
    def exportLiteralChildren(self, outfile, level, name_):
        showIndent(outfile, level)
        outfile.write('udbType=[\n')
        level += 1
        for udbType_ in self.udbType:
            showIndent(outfile, level)
            outfile.write('model_.UDBType(\n')
            udbType_.exportLiteral(outfile, level, name_='UDBType')
            showIndent(outfile, level)
            outfile.write('),\n')
        level -= 1
        showIndent(outfile, level)
        outfile.write('],\n')
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'udbType':
            obj_ = UDBType.factory()
            obj_.build(child_)
            self.udbType.append(obj_)
            obj_.original_tagname_ = 'udbType'
# end class UDBTypes


class Parameter(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, parameterName=None, udb_param_type=None, variable_name='NULL', description='no description', min='0.0', max='0.0', readonly=True):
        self.original_tagname_ = None
        self.parameterName = parameterName
        self.validate_ParamIdentifier(self.parameterName)
        self.udb_param_type = udb_param_type
        self.variable_name = variable_name
        self.description = description
        self.min = min
        self.max = max
        self.readonly = readonly
    def factory(*args_, **kwargs_):
        if Parameter.subclass:
            return Parameter.subclass(*args_, **kwargs_)
        else:
            return Parameter(*args_, **kwargs_)
    factory = staticmethod(factory)
    def get_parameterName(self): return self.parameterName
    def set_parameterName(self, parameterName): self.parameterName = parameterName
    def get_udb_param_type(self): return self.udb_param_type
    def set_udb_param_type(self, udb_param_type): self.udb_param_type = udb_param_type
    def get_variable_name(self): return self.variable_name
    def set_variable_name(self, variable_name): self.variable_name = variable_name
    def get_description(self): return self.description
    def set_description(self, description): self.description = description
    def get_min(self): return self.min
    def set_min(self, min): self.min = min
    def get_max(self): return self.max
    def set_max(self, max): self.max = max
    def get_readonly(self): return self.readonly
    def set_readonly(self, readonly): self.readonly = readonly
    def validate_ParamIdentifier(self, value):
        # Validate type ParamIdentifier, a restriction on xs:string.
        if value is not None and Validate_simpletypes_:
            if len(value) > 15:
                warnings_.warn('Value "%(value)s" does not match xsd maxLength restriction on ParamIdentifier' % {"value" : value.encode("utf-8")} )
            if len(value) < 1:
                warnings_.warn('Value "%(value)s" does not match xsd minLength restriction on ParamIdentifier' % {"value" : value.encode("utf-8")} )
    def hasContent_(self):
        if (
            self.parameterName is not None or
            self.udb_param_type is not None or
            self.variable_name != "NULL" or
            self.description != "no description" or
            self.min != "0.0" or
            self.max != "0.0" or
            not self.readonly
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='Parameter', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='Parameter')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='Parameter', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='Parameter'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='Parameter', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.parameterName is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sparameterName>%s</%sparameterName>%s' % (namespace_, self.gds_format_string(quote_xml(self.parameterName).encode(ExternalEncoding), input_name='parameterName'), namespace_, eol_))
        if self.udb_param_type is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sudb_param_type>%s</%sudb_param_type>%s' % (namespace_, self.gds_format_string(quote_xml(self.udb_param_type).encode(ExternalEncoding), input_name='udb_param_type'), namespace_, eol_))
        if self.variable_name != "NULL":
            showIndent(outfile, level, pretty_print)
            outfile.write('<%svariable_name>%s</%svariable_name>%s' % (namespace_, self.gds_format_string(quote_xml(self.variable_name).encode(ExternalEncoding), input_name='variable_name'), namespace_, eol_))
        if self.description != "no description":
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sdescription>%s</%sdescription>%s' % (namespace_, self.gds_format_string(quote_xml(self.description).encode(ExternalEncoding), input_name='description'), namespace_, eol_))
        if self.min != "0.0":
            showIndent(outfile, level, pretty_print)
            outfile.write('<%smin>%s</%smin>%s' % (namespace_, self.gds_format_string(quote_xml(self.min).encode(ExternalEncoding), input_name='min'), namespace_, eol_))
        if self.max != "0.0":
            showIndent(outfile, level, pretty_print)
            outfile.write('<%smax>%s</%smax>%s' % (namespace_, self.gds_format_string(quote_xml(self.max).encode(ExternalEncoding), input_name='max'), namespace_, eol_))
        if not self.readonly:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sreadonly>%s</%sreadonly>%s' % (namespace_, self.gds_format_boolean(self.readonly, input_name='readonly'), namespace_, eol_))
    def exportLiteral(self, outfile, level, name_='Parameter'):
        level += 1
        already_processed = set()
        self.exportLiteralAttributes(outfile, level, already_processed, name_)
        if self.hasContent_():
            self.exportLiteralChildren(outfile, level, name_)
    def exportLiteralAttributes(self, outfile, level, already_processed, name_):
        pass
    def exportLiteralChildren(self, outfile, level, name_):
        if self.parameterName is not None:
            showIndent(outfile, level)
            outfile.write('parameterName=%s,\n' % quote_python(self.parameterName).encode(ExternalEncoding))
        if self.udb_param_type is not None:
            showIndent(outfile, level)
            outfile.write('udb_param_type=%s,\n' % quote_python(self.udb_param_type).encode(ExternalEncoding))
        if self.variable_name is not None:
            showIndent(outfile, level)
            outfile.write('variable_name=%s,\n' % quote_python(self.variable_name).encode(ExternalEncoding))
        if self.description is not None:
            showIndent(outfile, level)
            outfile.write('description=%s,\n' % quote_python(self.description).encode(ExternalEncoding))
        if self.min is not None:
            showIndent(outfile, level)
            outfile.write('min=%s,\n' % quote_python(self.min).encode(ExternalEncoding))
        if self.max is not None:
            showIndent(outfile, level)
            outfile.write('max=%s,\n' % quote_python(self.max).encode(ExternalEncoding))
        if self.readonly is not None:
            showIndent(outfile, level)
            outfile.write('readonly=%s,\n' % self.readonly)
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'parameterName':
            parameterName_ = child_.text
            parameterName_ = self.gds_validate_string(parameterName_, node, 'parameterName')
            self.parameterName = parameterName_
            # validate type ParamIdentifier
            self.validate_ParamIdentifier(self.parameterName)
        elif nodeName_ == 'udb_param_type':
            udb_param_type_ = child_.text
            udb_param_type_ = self.gds_validate_string(udb_param_type_, node, 'udb_param_type')
            self.udb_param_type = udb_param_type_
        elif nodeName_ == 'variable_name':
            variable_name_ = child_.text
            variable_name_ = self.gds_validate_string(variable_name_, node, 'variable_name')
            self.variable_name = variable_name_
        elif nodeName_ == 'description':
            description_ = child_.text
            description_ = self.gds_validate_string(description_, node, 'description')
            self.description = description_
        elif nodeName_ == 'min':
            min_ = child_.text
            min_ = self.gds_validate_string(min_, node, 'min')
            self.min = min_
        elif nodeName_ == 'max':
            max_ = child_.text
            max_ = self.gds_validate_string(max_, node, 'max')
            self.max = max_
        elif nodeName_ == 'readonly':
            sval_ = child_.text
            if sval_ in ('true', '1'):
                ival_ = True
            elif sval_ in ('false', '0'):
                ival_ = False
            else:
                raise_parse_error(child_, 'requires boolean')
            ival_ = self.gds_validate_boolean(ival_, node, 'readonly')
            self.readonly = ival_
# end class Parameter


class Parameters(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, parameter=None):
        self.original_tagname_ = None
        if parameter is None:
            self.parameter = []
        else:
            self.parameter = parameter
    def factory(*args_, **kwargs_):
        if Parameters.subclass:
            return Parameters.subclass(*args_, **kwargs_)
        else:
            return Parameters(*args_, **kwargs_)
    factory = staticmethod(factory)
    def get_parameter(self): return self.parameter
    def set_parameter(self, parameter): self.parameter = parameter
    def add_parameter(self, value): self.parameter.append(value)
    def insert_parameter_at(self, index, value): self.parameter.insert(index, value)
    def replace_parameter_at(self, index, value): self.parameter[index] = value
    def hasContent_(self):
        if (
            self.parameter
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='Parameters', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='Parameters')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='Parameters', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='Parameters'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='Parameters', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        for parameter_ in self.parameter:
            parameter_.export(outfile, level, namespace_, name_='parameter', pretty_print=pretty_print)
    def exportLiteral(self, outfile, level, name_='Parameters'):
        level += 1
        already_processed = set()
        self.exportLiteralAttributes(outfile, level, already_processed, name_)
        if self.hasContent_():
            self.exportLiteralChildren(outfile, level, name_)
    def exportLiteralAttributes(self, outfile, level, already_processed, name_):
        pass
    def exportLiteralChildren(self, outfile, level, name_):
        showIndent(outfile, level)
        outfile.write('parameter=[\n')
        level += 1
        for parameter_ in self.parameter:
            showIndent(outfile, level)
            outfile.write('model_.Parameter(\n')
            parameter_.exportLiteral(outfile, level, name_='Parameter')
            showIndent(outfile, level)
            outfile.write('),\n')
        level -= 1
        showIndent(outfile, level)
        outfile.write('],\n')
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'parameter':
            obj_ = Parameter.factory()
            obj_.build(child_)
            self.parameter.append(obj_)
            obj_.original_tagname_ = 'parameter'
# end class Parameters


class ParameterBlock(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, blockName=None, storage_area='None', serialisationFlags=None, externs=None, includes=None, load_callback=None, in_mavlink_parameters=None, parameters=None, description='no description'):
        self.original_tagname_ = None
        self.blockName = blockName
        self.storage_area = storage_area
        self.serialisationFlags = serialisationFlags
        self.externs = externs
        self.includes = includes
        self.load_callback = load_callback
        self.in_mavlink_parameters = in_mavlink_parameters
        self.parameters = parameters
        self.description = description
    def factory(*args_, **kwargs_):
        if ParameterBlock.subclass:
            return ParameterBlock.subclass(*args_, **kwargs_)
        else:
            return ParameterBlock(*args_, **kwargs_)
    factory = staticmethod(factory)
    def get_blockName(self): return self.blockName
    def set_blockName(self, blockName): self.blockName = blockName
    def get_storage_area(self): return self.storage_area
    def set_storage_area(self, storage_area): self.storage_area = storage_area
    def get_serialisationFlags(self): return self.serialisationFlags
    def set_serialisationFlags(self, serialisationFlags): self.serialisationFlags = serialisationFlags
    def get_externs(self): return self.externs
    def set_externs(self, externs): self.externs = externs
    def get_includes(self): return self.includes
    def set_includes(self, includes): self.includes = includes
    def get_load_callback(self): return self.load_callback
    def set_load_callback(self, load_callback): self.load_callback = load_callback
    def get_in_mavlink_parameters(self): return self.in_mavlink_parameters
    def set_in_mavlink_parameters(self, in_mavlink_parameters): self.in_mavlink_parameters = in_mavlink_parameters
    def get_parameters(self): return self.parameters
    def set_parameters(self, parameters): self.parameters = parameters
    def get_description(self): return self.description
    def set_description(self, description): self.description = description
    def hasContent_(self):
        if (
            self.blockName is not None or
            self.storage_area != "None" or
            self.serialisationFlags is not None or
            self.externs is not None or
            self.includes is not None or
            self.load_callback is not None or
            self.in_mavlink_parameters is not None or
            self.parameters is not None or
            self.description != "no description"
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='ParameterBlock', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='ParameterBlock')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='ParameterBlock', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='ParameterBlock'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='ParameterBlock', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.blockName is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sblockName>%s</%sblockName>%s' % (namespace_, self.gds_format_string(quote_xml(self.blockName).encode(ExternalEncoding), input_name='blockName'), namespace_, eol_))
        if self.storage_area != "None":
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sstorage_area>%s</%sstorage_area>%s' % (namespace_, self.gds_format_string(quote_xml(self.storage_area).encode(ExternalEncoding), input_name='storage_area'), namespace_, eol_))
        if self.serialisationFlags is not None:
            self.serialisationFlags.export(outfile, level, namespace_, name_='serialisationFlags', pretty_print=pretty_print)
        if self.externs is not None:
            self.externs.export(outfile, level, namespace_, name_='externs', pretty_print=pretty_print)
        if self.includes is not None:
            self.includes.export(outfile, level, namespace_, name_='includes', pretty_print=pretty_print)
        if self.load_callback is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sload_callback>%s</%sload_callback>%s' % (namespace_, self.gds_format_string(quote_xml(self.load_callback).encode(ExternalEncoding), input_name='load_callback'), namespace_, eol_))
        if self.in_mavlink_parameters is not None:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sin_mavlink_parameters>%s</%sin_mavlink_parameters>%s' % (namespace_, self.gds_format_boolean(self.in_mavlink_parameters, input_name='in_mavlink_parameters'), namespace_, eol_))
        if self.parameters is not None:
            self.parameters.export(outfile, level, namespace_, name_='parameters', pretty_print=pretty_print)
        if self.description != "no description":
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sdescription>%s</%sdescription>%s' % (namespace_, self.gds_format_string(quote_xml(self.description).encode(ExternalEncoding), input_name='description'), namespace_, eol_))
    def exportLiteral(self, outfile, level, name_='ParameterBlock'):
        level += 1
        already_processed = set()
        self.exportLiteralAttributes(outfile, level, already_processed, name_)
        if self.hasContent_():
            self.exportLiteralChildren(outfile, level, name_)
    def exportLiteralAttributes(self, outfile, level, already_processed, name_):
        pass
    def exportLiteralChildren(self, outfile, level, name_):
        if self.blockName is not None:
            showIndent(outfile, level)
            outfile.write('blockName=%s,\n' % quote_python(self.blockName).encode(ExternalEncoding))
        if self.storage_area is not None:
            showIndent(outfile, level)
            outfile.write('storage_area=%s,\n' % quote_python(self.storage_area).encode(ExternalEncoding))
        if self.serialisationFlags is not None:
            showIndent(outfile, level)
            outfile.write('serialisationFlags=model_.SerialisationFlags(\n')
            self.serialisationFlags.exportLiteral(outfile, level, name_='serialisationFlags')
            showIndent(outfile, level)
            outfile.write('),\n')
        if self.externs is not None:
            showIndent(outfile, level)
            outfile.write('externs=model_.Externs(\n')
            self.externs.exportLiteral(outfile, level, name_='externs')
            showIndent(outfile, level)
            outfile.write('),\n')
        if self.includes is not None:
            showIndent(outfile, level)
            outfile.write('includes=model_.Includes(\n')
            self.includes.exportLiteral(outfile, level, name_='includes')
            showIndent(outfile, level)
            outfile.write('),\n')
        if self.load_callback is not None:
            showIndent(outfile, level)
            outfile.write('load_callback=%s,\n' % quote_python(self.load_callback).encode(ExternalEncoding))
        if self.in_mavlink_parameters is not None:
            showIndent(outfile, level)
            outfile.write('in_mavlink_parameters=%s,\n' % self.in_mavlink_parameters)
        if self.parameters is not None:
            showIndent(outfile, level)
            outfile.write('parameters=model_.Parameters(\n')
            self.parameters.exportLiteral(outfile, level, name_='parameters')
            showIndent(outfile, level)
            outfile.write('),\n')
        if self.description is not None:
            showIndent(outfile, level)
            outfile.write('description=%s,\n' % quote_python(self.description).encode(ExternalEncoding))
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'blockName':
            blockName_ = child_.text
            blockName_ = self.gds_validate_string(blockName_, node, 'blockName')
            self.blockName = blockName_
        elif nodeName_ == 'storage_area':
            storage_area_ = child_.text
            storage_area_ = self.gds_validate_string(storage_area_, node, 'storage_area')
            self.storage_area = storage_area_
        elif nodeName_ == 'serialisationFlags':
            obj_ = SerialisationFlags.factory()
            obj_.build(child_)
            self.serialisationFlags = obj_
            obj_.original_tagname_ = 'serialisationFlags'
        elif nodeName_ == 'externs':
            obj_ = Externs.factory()
            obj_.build(child_)
            self.externs = obj_
            obj_.original_tagname_ = 'externs'
        elif nodeName_ == 'includes':
            obj_ = Includes.factory()
            obj_.build(child_)
            self.includes = obj_
            obj_.original_tagname_ = 'includes'
        elif nodeName_ == 'load_callback':
            load_callback_ = child_.text
            load_callback_ = self.gds_validate_string(load_callback_, node, 'load_callback')
            self.load_callback = load_callback_
        elif nodeName_ == 'in_mavlink_parameters':
            sval_ = child_.text
            if sval_ in ('true', '1'):
                ival_ = True
            elif sval_ in ('false', '0'):
                ival_ = False
            else:
                raise_parse_error(child_, 'requires boolean')
            ival_ = self.gds_validate_boolean(ival_, node, 'in_mavlink_parameters')
            self.in_mavlink_parameters = ival_
        elif nodeName_ == 'parameters':
            obj_ = Parameters.factory()
            obj_.build(child_)
            self.parameters = obj_
            obj_.original_tagname_ = 'parameters'
        elif nodeName_ == 'description':
            description_ = child_.text
            description_ = self.gds_validate_string(description_, node, 'description')
            self.description = description_
# end class ParameterBlock


class ParameterBlocks(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, parameterBlock=None):
        self.original_tagname_ = None
        if parameterBlock is None:
            self.parameterBlock = []
        else:
            self.parameterBlock = parameterBlock
    def factory(*args_, **kwargs_):
        if ParameterBlocks.subclass:
            return ParameterBlocks.subclass(*args_, **kwargs_)
        else:
            return ParameterBlocks(*args_, **kwargs_)
    factory = staticmethod(factory)
    def get_parameterBlock(self): return self.parameterBlock
    def set_parameterBlock(self, parameterBlock): self.parameterBlock = parameterBlock
    def add_parameterBlock(self, value): self.parameterBlock.append(value)
    def insert_parameterBlock_at(self, index, value): self.parameterBlock.insert(index, value)
    def replace_parameterBlock_at(self, index, value): self.parameterBlock[index] = value
    def hasContent_(self):
        if (
            self.parameterBlock
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='ParameterBlocks', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='ParameterBlocks')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='ParameterBlocks', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='ParameterBlocks'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='ParameterBlocks', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        for parameterBlock_ in self.parameterBlock:
            parameterBlock_.export(outfile, level, namespace_, name_='parameterBlock', pretty_print=pretty_print)
    def exportLiteral(self, outfile, level, name_='ParameterBlocks'):
        level += 1
        already_processed = set()
        self.exportLiteralAttributes(outfile, level, already_processed, name_)
        if self.hasContent_():
            self.exportLiteralChildren(outfile, level, name_)
    def exportLiteralAttributes(self, outfile, level, already_processed, name_):
        pass
    def exportLiteralChildren(self, outfile, level, name_):
        showIndent(outfile, level)
        outfile.write('parameterBlock=[\n')
        level += 1
        for parameterBlock_ in self.parameterBlock:
            showIndent(outfile, level)
            outfile.write('model_.ParameterBlock(\n')
            parameterBlock_.exportLiteral(outfile, level, name_='ParameterBlock')
            showIndent(outfile, level)
            outfile.write('),\n')
        level -= 1
        showIndent(outfile, level)
        outfile.write('],\n')
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'parameterBlock':
            obj_ = ParameterBlock.factory()
            obj_.build(child_)
            self.parameterBlock.append(obj_)
            obj_.original_tagname_ = 'parameterBlock'
# end class ParameterBlocks


class ParameterDatabase(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, dataStorageAreas=None, serialisationFlags=None, udbTypes=None, parameterBlocks=None):
        self.original_tagname_ = None
        self.dataStorageAreas = dataStorageAreas
        self.serialisationFlags = serialisationFlags
        self.udbTypes = udbTypes
        self.parameterBlocks = parameterBlocks
    def factory(*args_, **kwargs_):
        if ParameterDatabase.subclass:
            return ParameterDatabase.subclass(*args_, **kwargs_)
        else:
            return ParameterDatabase(*args_, **kwargs_)
    factory = staticmethod(factory)
    def get_dataStorageAreas(self): return self.dataStorageAreas
    def set_dataStorageAreas(self, dataStorageAreas): self.dataStorageAreas = dataStorageAreas
    def get_serialisationFlags(self): return self.serialisationFlags
    def set_serialisationFlags(self, serialisationFlags): self.serialisationFlags = serialisationFlags
    def get_udbTypes(self): return self.udbTypes
    def set_udbTypes(self, udbTypes): self.udbTypes = udbTypes
    def get_parameterBlocks(self): return self.parameterBlocks
    def set_parameterBlocks(self, parameterBlocks): self.parameterBlocks = parameterBlocks
    def hasContent_(self):
        if (
            self.dataStorageAreas is not None or
            self.serialisationFlags is not None or
            self.udbTypes is not None or
            self.parameterBlocks is not None
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='ParameterDatabase', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='ParameterDatabase')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='ParameterDatabase', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='ParameterDatabase'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='ParameterDatabase', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.dataStorageAreas is not None:
            self.dataStorageAreas.export(outfile, level, namespace_, name_='dataStorageAreas', pretty_print=pretty_print)
        if self.serialisationFlags is not None:
            self.serialisationFlags.export(outfile, level, namespace_, name_='serialisationFlags', pretty_print=pretty_print)
        if self.udbTypes is not None:
            self.udbTypes.export(outfile, level, namespace_, name_='udbTypes', pretty_print=pretty_print)
        if self.parameterBlocks is not None:
            self.parameterBlocks.export(outfile, level, namespace_, name_='parameterBlocks', pretty_print=pretty_print)
    def exportLiteral(self, outfile, level, name_='ParameterDatabase'):
        level += 1
        already_processed = set()
        self.exportLiteralAttributes(outfile, level, already_processed, name_)
        if self.hasContent_():
            self.exportLiteralChildren(outfile, level, name_)
    def exportLiteralAttributes(self, outfile, level, already_processed, name_):
        pass
    def exportLiteralChildren(self, outfile, level, name_):
        if self.dataStorageAreas is not None:
            showIndent(outfile, level)
            outfile.write('dataStorageAreas=model_.DataStorageAreas(\n')
            self.dataStorageAreas.exportLiteral(outfile, level, name_='dataStorageAreas')
            showIndent(outfile, level)
            outfile.write('),\n')
        if self.serialisationFlags is not None:
            showIndent(outfile, level)
            outfile.write('serialisationFlags=model_.SerialisationFlags(\n')
            self.serialisationFlags.exportLiteral(outfile, level, name_='serialisationFlags')
            showIndent(outfile, level)
            outfile.write('),\n')
        if self.udbTypes is not None:
            showIndent(outfile, level)
            outfile.write('udbTypes=model_.UDBTypes(\n')
            self.udbTypes.exportLiteral(outfile, level, name_='udbTypes')
            showIndent(outfile, level)
            outfile.write('),\n')
        if self.parameterBlocks is not None:
            showIndent(outfile, level)
            outfile.write('parameterBlocks=model_.ParameterBlocks(\n')
            self.parameterBlocks.exportLiteral(outfile, level, name_='parameterBlocks')
            showIndent(outfile, level)
            outfile.write('),\n')
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'dataStorageAreas':
            obj_ = DataStorageAreas.factory()
            obj_.build(child_)
            self.dataStorageAreas = obj_
            obj_.original_tagname_ = 'dataStorageAreas'
        elif nodeName_ == 'serialisationFlags':
            obj_ = SerialisationFlags.factory()
            obj_.build(child_)
            self.serialisationFlags = obj_
            obj_.original_tagname_ = 'serialisationFlags'
        elif nodeName_ == 'udbTypes':
            obj_ = UDBTypes.factory()
            obj_.build(child_)
            self.udbTypes = obj_
            obj_.original_tagname_ = 'udbTypes'
        elif nodeName_ == 'parameterBlocks':
            obj_ = ParameterBlocks.factory()
            obj_.build(child_)
            self.parameterBlocks = obj_
            obj_.original_tagname_ = 'parameterBlocks'
# end class ParameterDatabase


class Externs(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, externString=None):
        self.original_tagname_ = None
        if externString is None:
            self.externString = []
        else:
            self.externString = externString
    def factory(*args_, **kwargs_):
        if Externs.subclass:
            return Externs.subclass(*args_, **kwargs_)
        else:
            return Externs(*args_, **kwargs_)
    factory = staticmethod(factory)
    def get_externString(self): return self.externString
    def set_externString(self, externString): self.externString = externString
    def add_externString(self, value): self.externString.append(value)
    def insert_externString_at(self, index, value): self.externString.insert(index, value)
    def replace_externString_at(self, index, value): self.externString[index] = value
    def hasContent_(self):
        if (
            self.externString
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='Externs', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='Externs')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='Externs', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='Externs'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='Externs', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        for externString_ in self.externString:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sexternString>%s</%sexternString>%s' % (namespace_, self.gds_format_string(quote_xml(externString_).encode(ExternalEncoding), input_name='externString'), namespace_, eol_))
    def exportLiteral(self, outfile, level, name_='Externs'):
        level += 1
        already_processed = set()
        self.exportLiteralAttributes(outfile, level, already_processed, name_)
        if self.hasContent_():
            self.exportLiteralChildren(outfile, level, name_)
    def exportLiteralAttributes(self, outfile, level, already_processed, name_):
        pass
    def exportLiteralChildren(self, outfile, level, name_):
        showIndent(outfile, level)
        outfile.write('externString=[\n')
        level += 1
        for externString_ in self.externString:
            showIndent(outfile, level)
            outfile.write('%s,\n' % quote_python(externString_).encode(ExternalEncoding))
        level -= 1
        showIndent(outfile, level)
        outfile.write('],\n')
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'externString':
            externString_ = child_.text
            externString_ = self.gds_validate_string(externString_, node, 'externString')
            self.externString.append(externString_)
# end class Externs


class Includes(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, includeString=None):
        self.original_tagname_ = None
        if includeString is None:
            self.includeString = []
        else:
            self.includeString = includeString
    def factory(*args_, **kwargs_):
        if Includes.subclass:
            return Includes.subclass(*args_, **kwargs_)
        else:
            return Includes(*args_, **kwargs_)
    factory = staticmethod(factory)
    def get_includeString(self): return self.includeString
    def set_includeString(self, includeString): self.includeString = includeString
    def add_includeString(self, value): self.includeString.append(value)
    def insert_includeString_at(self, index, value): self.includeString.insert(index, value)
    def replace_includeString_at(self, index, value): self.includeString[index] = value
    def hasContent_(self):
        if (
            self.includeString
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='Includes', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='Includes')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='Includes', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='Includes'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='Includes', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        for includeString_ in self.includeString:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sincludeString>%s</%sincludeString>%s' % (namespace_, self.gds_format_string(quote_xml(includeString_).encode(ExternalEncoding), input_name='includeString'), namespace_, eol_))
    def exportLiteral(self, outfile, level, name_='Includes'):
        level += 1
        already_processed = set()
        self.exportLiteralAttributes(outfile, level, already_processed, name_)
        if self.hasContent_():
            self.exportLiteralChildren(outfile, level, name_)
    def exportLiteralAttributes(self, outfile, level, already_processed, name_):
        pass
    def exportLiteralChildren(self, outfile, level, name_):
        showIndent(outfile, level)
        outfile.write('includeString=[\n')
        level += 1
        for includeString_ in self.includeString:
            showIndent(outfile, level)
            outfile.write('%s,\n' % quote_python(includeString_).encode(ExternalEncoding))
        level -= 1
        showIndent(outfile, level)
        outfile.write('],\n')
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'includeString':
            includeString_ = child_.text
            includeString_ = self.gds_validate_string(includeString_, node, 'includeString')
            self.includeString.append(includeString_)
# end class Includes


class DataStorageAreas(GeneratedsSuper):
    subclass = None
    superclass = None
    def __init__(self, dataStorageArea=None):
        self.original_tagname_ = None
        if dataStorageArea is None:
            self.dataStorageArea = []
        else:
            self.dataStorageArea = dataStorageArea
    def factory(*args_, **kwargs_):
        if DataStorageAreas.subclass:
            return DataStorageAreas.subclass(*args_, **kwargs_)
        else:
            return DataStorageAreas(*args_, **kwargs_)
    factory = staticmethod(factory)
    def get_dataStorageArea(self): return self.dataStorageArea
    def set_dataStorageArea(self, dataStorageArea): self.dataStorageArea = dataStorageArea
    def add_dataStorageArea(self, value): self.dataStorageArea.append(value)
    def insert_dataStorageArea_at(self, index, value): self.dataStorageArea.insert(index, value)
    def replace_dataStorageArea_at(self, index, value): self.dataStorageArea[index] = value
    def hasContent_(self):
        if (
            self.dataStorageArea
        ):
            return True
        else:
            return False
    def export(self, outfile, level, namespace_='', name_='DataStorageAreas', namespacedef_='', pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        if self.original_tagname_ is not None:
            name_ = self.original_tagname_
        showIndent(outfile, level, pretty_print)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        already_processed = set()
        self.exportAttributes(outfile, level, already_processed, namespace_, name_='DataStorageAreas')
        if self.hasContent_():
            outfile.write('>%s' % (eol_, ))
            self.exportChildren(outfile, level + 1, namespace_='', name_='DataStorageAreas', pretty_print=pretty_print)
            showIndent(outfile, level, pretty_print)
            outfile.write('</%s%s>%s' % (namespace_, name_, eol_))
        else:
            outfile.write('/>%s' % (eol_, ))
    def exportAttributes(self, outfile, level, already_processed, namespace_='', name_='DataStorageAreas'):
        pass
    def exportChildren(self, outfile, level, namespace_='', name_='DataStorageAreas', fromsubclass_=False, pretty_print=True):
        if pretty_print:
            eol_ = '\n'
        else:
            eol_ = ''
        for dataStorageArea_ in self.dataStorageArea:
            showIndent(outfile, level, pretty_print)
            outfile.write('<%sdataStorageArea>%s</%sdataStorageArea>%s' % (namespace_, self.gds_format_string(quote_xml(dataStorageArea_).encode(ExternalEncoding), input_name='dataStorageArea'), namespace_, eol_))
    def exportLiteral(self, outfile, level, name_='DataStorageAreas'):
        level += 1
        already_processed = set()
        self.exportLiteralAttributes(outfile, level, already_processed, name_)
        if self.hasContent_():
            self.exportLiteralChildren(outfile, level, name_)
    def exportLiteralAttributes(self, outfile, level, already_processed, name_):
        pass
    def exportLiteralChildren(self, outfile, level, name_):
        showIndent(outfile, level)
        outfile.write('dataStorageArea=[\n')
        level += 1
        for dataStorageArea_ in self.dataStorageArea:
            showIndent(outfile, level)
            outfile.write('%s,\n' % quote_python(dataStorageArea_).encode(ExternalEncoding))
        level -= 1
        showIndent(outfile, level)
        outfile.write('],\n')
    def build(self, node):
        already_processed = set()
        self.buildAttributes(node, node.attrib, already_processed)
        for child in node:
            nodeName_ = Tag_pattern_.match(child.tag).groups()[-1]
            self.buildChildren(child, node, nodeName_)
        return self
    def buildAttributes(self, node, attrs, already_processed):
        pass
    def buildChildren(self, child_, node, nodeName_, fromsubclass_=False):
        if nodeName_ == 'dataStorageArea':
            dataStorageArea_ = child_.text
            dataStorageArea_ = self.gds_validate_string(dataStorageArea_, node, 'dataStorageArea')
            self.dataStorageArea.append(dataStorageArea_)
# end class DataStorageAreas


GDSClassesMapping = {
    'parameters': Parameters,
    'udbType': UDBType,
    'udbTypes': UDBTypes,
    'externs': Externs,
    'includes': Includes,
    'serialisationFlags': SerialisationFlags,
    'dataStorageAreas': DataStorageAreas,
    'parameterBlock': ParameterBlock,
    'parameterBlocks': ParameterBlocks,
    'parameter': Parameter,
}


USAGE_TEXT = """
Usage: python <Parser>.py [ -s ] <in_xml_file>
"""


def usage():
    print(USAGE_TEXT)
    sys.exit(1)


def get_root_tag(node):
    tag = Tag_pattern_.match(node.tag).groups()[-1]
    rootClass = GDSClassesMapping.get(tag)
    if rootClass is None:
        rootClass = globals().get(tag)
    return tag, rootClass


def parse(inFileName, silence=False):
    doc = parsexml_(inFileName)
    rootNode = doc.getroot()
    rootTag, rootClass = get_root_tag(rootNode)
    if rootClass is None:
        rootTag = 'SerialisationFlags'
        rootClass = SerialisationFlags
    rootObj = rootClass.factory()
    rootObj.build(rootNode)
    # Enable Python to collect the space used by the DOM.
    doc = None
    if not silence:
        sys.stdout.write('<?xml version="1.0" ?>\n')
        rootObj.export(
            sys.stdout, 0, name_=rootTag,
            namespacedef_='',
            pretty_print=True)
    return rootObj


def parseEtree(inFileName, silence=False):
    doc = parsexml_(inFileName)
    rootNode = doc.getroot()
    rootTag, rootClass = get_root_tag(rootNode)
    if rootClass is None:
        rootTag = 'SerialisationFlags'
        rootClass = SerialisationFlags
    rootObj = rootClass.factory()
    rootObj.build(rootNode)
    # Enable Python to collect the space used by the DOM.
    doc = None
    mapping = {}
    rootElement = rootObj.to_etree(None, name_=rootTag, mapping_=mapping)
    reverse_mapping = rootObj.gds_reverse_node_mapping(mapping)
    if not silence:
        content = etree_.tostring(
            rootElement, pretty_print=True,
            xml_declaration=True, encoding="utf-8")
        sys.stdout.write(content)
        sys.stdout.write('\n')
    return rootObj, rootElement, mapping, reverse_mapping


def parseString(inString, silence=False):
    from StringIO import StringIO
    doc = parsexml_(StringIO(inString))
    rootNode = doc.getroot()
    rootTag, rootClass = get_root_tag(rootNode)
    if rootClass is None:
        rootTag = 'SerialisationFlags'
        rootClass = SerialisationFlags
    rootObj = rootClass.factory()
    rootObj.build(rootNode)
    # Enable Python to collect the space used by the DOM.
    doc = None
    if not silence:
        sys.stdout.write('<?xml version="1.0" ?>\n')
        rootObj.export(
            sys.stdout, 0, name_=rootTag,
            namespacedef_='')
    return rootObj


def parseLiteral(inFileName, silence=False):
    doc = parsexml_(inFileName)
    rootNode = doc.getroot()
    rootTag, rootClass = get_root_tag(rootNode)
    if rootClass is None:
        rootTag = 'SerialisationFlags'
        rootClass = SerialisationFlags
    rootObj = rootClass.factory()
    rootObj.build(rootNode)
    # Enable Python to collect the space used by the DOM.
    doc = None
    if not silence:
        sys.stdout.write('#from ParameterDatabase import *\n\n')
        sys.stdout.write('import ParameterDatabase as model_\n\n')
        sys.stdout.write('rootObj = model_.rootClass(\n')
        rootObj.exportLiteral(sys.stdout, 0, name_=rootTag)
        sys.stdout.write(')\n')
    return rootObj


def main():
    args = sys.argv[1:]
    if len(args) == 1:
        parse(args[0])
    else:
        usage()


if __name__ == '__main__':
    #import pdb; pdb.set_trace()
    main()


__all__ = [
    "DataStorageAreas",
    "Externs",
    "Includes",
    "Parameter",
    "ParameterBlock",
    "ParameterBlocks",
    "ParameterDatabase",
    "Parameters",
    "SerialisationFlags",
    "UDBType",
    "UDBTypes"
]
