#ifndef FLEXIFUNCTION_REGISTERS_H
#define FLEXIFUNCTION_REGISTERS_H
// pyFEdit generated file - DO NOT EDIT


typedef enum
{
VIRTUAL_INPUT_PWIN_ROLL,
VIRTUAL_INPUT_PWIN_PITCH,
VIRTUAL_INPUT_PWIN_YAW,
VIRTUAL_INPUT_PWIN_THROTTLE,
VIRTUAL_INPUT_PWIN_FLAP,
VIRTUAL_INPUT_PWIN_CAMBER,
VIRTUAL_INPUT_PWIN_BRAKE,
VIRTUAL_INPUT_APCON_ROLL,
VIRTUAL_INPUT_APCON_PITCH,
VIRTUAL_INPUT_APCON_YAW,
VIRTUAL_INPUT_APCON_THROTTLE,
VIRTUAL_INPUT_APCON_FLAP,
VIRTUAL_INPUT_APCON_CAMBER,
VIRTUAL_INPUT_APCON_BRAKE,
VIRTUAL_INPUT_APCON_WAGGLE,
VIRTUAL_INPUT_APMODE_FULL,
VIRTUAL_INPUT_RADIO_MANUAL_MODE,
VIRTUAL_INPUT_APMODE_RADIO_ON,
VIRTUAL_INPUT_GAIN_MAN_MIX,
VIRTUAL_INPUT_TRIM_POINT,
VIRTUAL_INPUT_TRIM_THROTTLE,
};

typedef enum
{
VIRTUAL_OUTPUT_AILERON_L,
VIRTUAL_OUTPUT_ELEVATOR,
VIRTUAL_OUTPUT_THROTTLE,
VIRTUAL_OUTPUT_RUDDER,
VIRTUAL_OUTPUT_AILERON_R,
VIRTUAL_OUTPUT_FLAPMID_L,
VIRTUAL_OUTPUT_FLAPMID_R,
VIRTUAL_OUTPUT_FLAP_L,
VIRTUAL_OUTPUT_FLAP_R,
VIRTUAL_OUTPUT_SPOILER,
};

#endif
