#ifndef FLEXIFUNCTION_REGISTERS_H
#define FLEXIFUNCTION_REGISTERS_H
// pyFEdit generated file - DO NOT EDIT


typedef enum
{
VIRTUAL_INPUT_CON_ROLL,
VIRTUAL_INPUT_CON_PITCH,
VIRTUAL_INPUT_CON_YAW,
VIRTUAL_INPUT_CON_THROTTLE,
VIRTUAL_INPUT_CON_FLAP,
VIRTUAL_INPUT_CON_CAMBER,
VIRTUAL_INPUT_CON_BRAKE,
VIRTUAL_INPUT_APCON_WAGGLE,
};

typedef enum
{
VIRTUAL_OUTPUT_AILERON_L,
VIRTUAL_OUTPUT_ELEVATOR,
VIRTUAL_OUTPUT_THROTTLE,
VIRTUAL_OUTPUT_RUDDER,
VIRTUAL_OUTPUT_AILERON_R,
VIRTUAL_OUTPUT_FLAPMID_L,
VIRTUAL_OUTPUT_FLAPMID_R,
VIRTUAL_OUTPUT_FLAP_L,
VIRTUAL_OUTPUT_FLAP_R,
VIRTUAL_OUTPUT_SPOILER,
};

#endif
